name: medsal
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.5.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.10.0
  firebase_database: ^10.0.6
  firebase_storage: ^11.0.8
  flutter:
    sdk: flutter
  fluttericon: ^2.0.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  icon: ^2.2.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  shared_preferences: ^2.0.15
  tabler_icons: ^0.0.3
  typicons_flutter: ^0.5.0
  url_launcher: ^6.1.0
  http: ^1.2.1
  crypto: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
