// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBunTO0wLKeAQE4B94Bk0Fs4N-AOtofqMI',
    appId: '1:679447374543:web:c731a85c0788e30be0e5ba',
    messagingSenderId: '679447374543',
    projectId: 'medsalud-f54e2',
    authDomain: 'medsalud-f54e2.firebaseapp.com',
    storageBucket: 'medsalud-f54e2.appspot.com',
    measurementId: 'G-QVFP9Y66JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs9ulDcIhhwlBzwVJQIoiuVtOPxd0nlG8',
    appId: '1:679447374543:android:edda665eb04cf35ee0e5ba',
    messagingSenderId: '679447374543',
    projectId: 'medsalud-f54e2',
    storageBucket: 'medsalud-f54e2.appspot.com',
  );


  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBunTO0wLKeAQE4B94Bk0Fs4N-AOtofqMI',
    appId: '1:679447374543:web:67b81f7810b429bde0e5ba',
    messagingSenderId: '679447374543',
    projectId: 'medsalud-f54e2',
    authDomain: 'medsalud-f54e2.firebaseapp.com',
    storageBucket: 'medsalud-f54e2.appspot.com',
    measurementId: 'G-HV44DCL8TZ',
  );

}